---
title: "Teste gif óbitos por estado"
output:
  html_document:
  toc: true
toc_float: true
code_folding: hide
---
  
```{r message=FALSE, warning=FALSE, paged.print=FALSE}

library("tidyverse")
library("cowplot")
library("plotly")
library("gganimate")
library("RColorBrewer")
library("transformr")
library("readr")

casos <- read_csv("../../dados_processados/integridade_SIVEP/dados_covid_br.csv")
obs <- read_csv("../../dados_processados/integridade_SIVEP/dados_obcovid_br.csv")

casos<-casos %>%
  filter(dt_sin_pri >=  "2020-01-01")
obs<-obs %>%
  filter(dt_evoluca >=  "2020-01-01")
last_data_casos<-max(casos$data)
last_data_obs<-max(obs$data)
# Setting locale to Brasil
Sys.setlocale(category = "LC_TIME", locale = "pt_BR.UTF-8")

```


```{r gif Brasil casos}
## Gif casos ##
nowc <-
  ggplot(data = casos, aes(x = dt_sin_pri, y = n, col = as.factor(data))) +
  # geom_col(width = 1,position = position_stack(reverse = TRUE))+
  geom_line()+
  scale_x_date(date_labels = "%d/%B", date_breaks = "2 month") +
  scale_color_viridis_d(direction = 1,
                        aesthetics = "colour",
                         option = "viridis") +
  labs(x = "Data do 1º Sintoma", y = "Número de Casos", 
       colour = "Data da Base", 
       title = "Evolução de Nº de Casos", 
       subtitle = "Observatório COVID19 BR; covid19br.github.io",
       caption = paste0("Fonte: SIVEP-Gripe até a base do dia ", last_data)) +
  theme_cowplot() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, size = 22),
        plot.subtitle = element_text(hjust = 0.5, size = 18),
        axis.text.x = element_text(size = 16, angle = 90),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face = "bold"),)+
  # facet_wrap(~sg_uf,
  #            scales = "free",
  #            nrow = 3)
  transition_states(factor(data))+
  shadow_mark(colour = "lightgrey",
              alpha = 0.5,
              size = .7,
              exclude_layer = c(2, 3))

animate(nowc,
        duration = 20,
        end_pause = 5,
        width = 800,
        height = 600)

```

```{r gif Brasil obs}
## Gif obitos ##
nowo <-
  ggplot(data = obs, aes(x = dt_evoluca, y = n, col = as.factor(data))) +
  # geom_col(width = 1,position = position_stack(reverse = TRUE))+
  geom_line()+
  scale_x_date(date_labels = "%d/%B", date_breaks = "2 month") +
  scale_color_viridis_d(direction = 1,
                        aesthetics = "colour",
                         option = "viridis") +
  labs(x = "Data do Óbito", y = "Número de Óbitos", 
       colour = "Data da Base", 
       title = "Evolução de Nº de Óbitos", 
       subtitle = "Observatório COVID19 BR; covid19br.github.io",
       caption = paste0("Fonte: SIVEP-Gripe até a base do dia ", last_data)) +
  theme_cowplot() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, size = 22),
        plot.subtitle = element_text(hjust = 0.5, size = 18),
        axis.text.x = element_text(size = 16, angle = 90),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face = "bold"),)+
  # facet_wrap(~sg_uf,
  #            scales = "free",
  #            nrow = 3)
  transition_states(factor(data))+
  shadow_mark(colour = "lightgrey",
              alpha = 0.5,
              size = .7,
              exclude_layer = c(2, 3))

animate(nowo,
        duration = 20,
        end_pause = 5,
        width = 800,
        height = 600)

```


```{r Por_regioes}
dados<- dados %>%
mutate(Region = case_when(sg_uf == "RS" | sg_uf == "SC" | sg_uf == "PR" ~ "Região Sul",
          sg_uf == "SP" | sg_uf == "MG" | sg_uf == "RJ" | sg_uf == "ES" ~ "Região Sudeste",
        sg_uf == "MS" | sg_uf == "MT" | sg_uf == "GO" | sg_uf == "DF" ~ "Região Centro-Oeste",
        sg_uf == "AC" | sg_uf == "AM" | sg_uf == "RO" | sg_uf == "RR" | sg_uf == "PA" | sg_uf == "TO" | sg_uf == "AP" ~ "Região Norte",
        sg_uf == "BA" | sg_uf == "PE" | sg_uf == "SE" | sg_uf == "CE" | sg_uf == "PI" | sg_uf == "MA" | sg_uf == "AL" | sg_uf == "RN" | sg_uf == "PB" ~ "Região Nordeste")) %>%
as.data.frame()


regiao_sul<-dados %>% 
  filter(sg_uf == "RS" | sg_uf == "SC" | sg_uf == "PR") %>% 
  as.data.frame()

regiao_sudeste<-dados %>% 
  filter(sg_uf == "SP" | sg_uf == "MG" | sg_uf == "RJ" | sg_uf == "ES") %>% 
  as.data.frame()

regiao_centro_oeste <- dados %>% 
  filter(sg_uf == "MS" | sg_uf == "MT" | sg_uf == "GO" | sg_uf == "DF") %>% 
  as.data.frame()

regiao_norte <- dados %>% 
  filter(sg_uf == "AC" | sg_uf == "AM" | sg_uf == "RO" | sg_uf == "RR" | sg_uf == "PA" | sg_uf == "TO") %>% 
  as.data.frame()

regiao_nordeste <- dados %>% 
  filter(sg_uf == "BA" | sg_uf == "PE" | sg_uf == "SE" | sg_uf == "CE" | sg_uf == "PI" | sg_uf == "MA" | sg_uf == "AL" | sg_uf == "RN" | sg_uf == "PB") %>% 
  as.data.frame()
```

#######################################################################
REGIÃO sUL
#######################################################################

```{r região sul}
  re_sul <-
  ggplot(data = regiao_sul) +
  geom_line(aes(x = dt_evoluca, y = n, colour = factor(data)), size = .7) +
  scale_x_date(date_labels = "%d/%B") +
  scale_colour_viridis_d(direction = -1) +
  labs(x = "Data do Óbito", y = "Número de Óbitos", 
       # colour = "Data do Boletim", 
       title = "Evolução de Óbitos por Data de Óbito - Região Sul", 
       subtitle = "Observatório COVID19 BR; covid19br.github.io",
       caption = paste0("Fonte: SIVEP-Gripe até a base do dia ", last_data)) +
  theme_cowplot() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, size = 22),
        plot.subtitle = element_text(hjust = 0.5, size = 18),
        axis.text.x = element_text(size = 16, angle = 90),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face = "bold"),) +
  facet_wrap(~sg_uf, 
             scales = "free")
  # transition_states(factor(data))+
  # shadow_mark(colour = "lightgrey",
  #             alpha = 0.5,
  #             size = .7,
  #             exclude_layer = c(2, 3))

# animate(re_sul,
#         duration = 20,
#         end_pause = 5,
#         width = 800,
#         height = 800)

```

#######################################################################
REGIÃO SUDESTE
#######################################################################

```{r região sudeste}
  re_sudeste <-
  ggplot(data = regiao_sudeste) +
  geom_line(aes(x = dt_evoluca, y = n, colour = factor(data)), size = .7) +
  scale_x_date(date_labels = "%d/%B") +
  scale_colour_viridis_d(direction = -1) +
  labs(x = "Data do Óbito", y = "Número de Óbitos", 
       # colour = "Data do Boletim", 
       title = "Evolução de Óbitos por Data de Óbito - Região Sudeste", 
       subtitle = "Observatório COVID19 BR; covid19br.github.io",
       caption = paste0("Fonte: SIVEP-Gripe até a base do dia ", last_data)) +
  theme_cowplot() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, size = 22),
        plot.subtitle = element_text(hjust = 0.5, size = 18),
        axis.text.x = element_text(size = 16, angle = 90),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face = "bold"),) +
  facet_wrap(~sg_uf, 
             scales = "free")
  # transition_states(factor(data))+
  # shadow_mark(colour = "lightgrey",
  #             alpha = 0.5,
  #             size = .7,
  #             exclude_layer = c(2, 3))

# animate(re_sudeste,
#         duration = 20,
#         end_pause = 5,
#         width = 800,
#         height = 800)

```

#######################################################################
REGIÃO CENTRO-OESTE
#######################################################################

```{r região centro_oeste}
  re_centro_oeste <-
  ggplot(data = regiao_centro_oeste) +
  geom_line(aes(x = dt_evoluca, y = n, colour = factor(data)), size = .7) +
  scale_x_date(date_labels = "%d/%B") +
  scale_colour_viridis_d(direction = -1) +
  labs(x = "Data do Óbito", y = "Número de Óbitos", 
       # colour = "Data do Boletim", 
       title = "Evolução de Óbitos por Data de Óbito - Região Centro-Oeste", 
       subtitle = "Observatório COVID19 BR; covid19br.github.io",
       caption = paste0("Fonte: SIVEP-Gripe até a base do dia ", last_data)) +
  theme_cowplot() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, size = 22),
        plot.subtitle = element_text(hjust = 0.5, size = 18),
        axis.text.x = element_text(size = 16, angle = 90),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face = "bold"),) +
  facet_wrap(~sg_uf, 
             scales = "free")
#   transition_states(factor(data))+
#   shadow_mark(colour = "lightgrey",
#               alpha = 0.5,
#               size = .7,
#               exclude_layer = c(2, 3))
# 
# animate(re_centro_oeste,
#         duration = 20,
#         end_pause = 5,
#         width = 800,
#         height = 800)

```

#######################################################################
REGIÃO NORTE
#######################################################################

```{r região norte}
  re_norte <-
  ggplot(data = regiao_norte) +
  geom_line(aes(x = dt_evoluca, y = n, colour = factor(data)), size = .7) +
  scale_x_date(date_labels = "%d/%B") +
  scale_colour_viridis_d(direction = -1) +
  labs(x = "Data do Óbito", y = "Número de Óbitos", 
       # colour = "Data do Boletim", 
       title = "Evolução de Óbitos por Data de Óbito - Região Norte", 
       subtitle = "Observatório COVID19 BR; covid19br.github.io",
       caption = paste0("Fonte: SIVEP-Gripe até a base do dia ", last_data)) +
  theme_cowplot() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, size = 22),
        plot.subtitle = element_text(hjust = 0.5, size = 18),
        axis.text.x = element_text(size = 16, angle = 90),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face = "bold"),) +
  facet_wrap(~sg_uf, 
             scales = "free",
             nrow = 3)
#   transition_states(factor(data))+
#   shadow_mark(colour = "lightgrey",
#               alpha = 0.5,
#               size = .7,
#               exclude_layer = c(2, 3))
# 
# animate(re_norte,
#         duration = 20,
#         end_pause = 5,
#         width = 800,
#         height = 800)

```

#######################################################################
REGIÃO NORDESTE
#######################################################################

```{r região nordeste}
  re_nordeste <-
  ggplot(data = regiao_nordeste) +
  geom_line(aes(x = dt_evoluca, y = n, colour = factor(data)), size = .7) +
  scale_x_date(date_labels = "%d/%B") +
  scale_colour_viridis_d(direction = -1) +
  labs(x = "Data do Óbito", y = "Número de Óbitos", 
       # colour = "Data do Boletim", 
       title = "Evolução de Óbitos por Data de Óbito - Região Nordeste", 
       subtitle = "Observatório COVID19 BR; covid19br.github.io",
       caption = paste0("Fonte: SIVEP-Gripe até a base do dia ", last_data)) +
  theme_cowplot() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, size = 22),
        plot.subtitle = element_text(hjust = 0.5, size = 18),
        axis.text.x = element_text(size = 16, angle = 90),
        axis.text.y = element_text(size = 16),
        axis.title.x = element_text(size = 18, face = "bold"),
        axis.title.y = element_text(size = 18, face = "bold"),) +
  facet_wrap(~sg_uf, 
             scales = "free",
             nrow = 3)
#   transition_states(factor(data))+
#   shadow_mark(colour = "lightgrey",
#               alpha = 0.5,
#               size = .7,
#               exclude_layer = c(2, 3))
# 
# animate(re_nordeste,
#         duration = 20,
#         end_pause = 5,
#         width = 800,
#         height = 800)

```